service: scaleway-golang
configValidationMode: off
provider:
  name: scaleway
  runtime: go113 # Available go runtimes are listed in documentation
  # Global Environment variables - used in every functions
  env:
    test: test
  # the path to the credentials file needs to be absolute
  scwToken: <scw-token>
  scwProject: <scw-project-id>
  # region in which the deployment will happen
  scwRegion: fr-par

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'

functions:
  first:
    # If handler is at the root of your serverless project
    handler: "."
    # Local environment variables - used only in given function
    env:
      local: local

  mypackage:
    # if your handler is in a custom package
    handler: mypackage
